Traceback (most recent call last):
  File "/Users/julia/dev/GitHub/boringStuffPython/raiseAssertStatements.py", line 26, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "/Users/julia/dev/GitHub/boringStuffPython/raiseAssertStatements.py", line 26, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "/Users/julia/dev/GitHub/boringStuffPython/raiseAssertStatements.py", line 26, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
